name: "Devin Security Sentinel"
description: "Runs Devin-based remediation on active GitHub security alerts in a given repo"

branding:
  icon: "shield"
  color: "blue"

inputs:
  owner:
    description: "Repository owner"
    required: true

  repo:
    description: "Repository name"
    required: true

  branch:
    description: "Branch to analyze (optional)"
    required: false
    default: ""

  github_token:
    description: "GitHub Personal Access Token (classic required with full repo scope)"
    required: true

  devin_api_key:
    description: "Devin API key"
    required: true

  slack_bot_token:
    description: "Slack bot OAuth Token if user wishes to send slack messages"
    required: false

  slack_channel_id:
    description: "Slack channel id to send slack messages if needed"
    required: false
    default: ""

outputs:
  alerts_found:
    description: "Number of active alerts found"
    value: ${{ steps.run-orchestrator.outputs.alerts_found }}
  batches_created:
    description: "Number of remediation batches created"
    value: ${{ steps.run-orchestrator.outputs.batches_created }}
  status:
    description: "Execution status (success, no_alerts, failed)"
    value: ${{ steps.run-orchestrator.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r "${{ github.action_path }}/requirements.txt"

    - name: Run Devin Orchestrator
      id: run-orchestrator
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        DEVIN_API_KEY: ${{ inputs.devin_api_key }}
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
   
      run: |
        python "${{ github.action_path }}/main.py" \
          "${{ inputs.owner }}" \
          "${{ inputs.repo }}" \
          "${{ inputs.branch }}" \
          "${{ inputs.slack_channel_id }}"
          
