name: "Devin Security Orchestration (Two Jobs)"
description: "If you want to run CodeQL and Devin Security Orchestrator as separate jobs,
this is a sample format you can put in your .github/workflows/ directory to run the action"
paste this into your already exisiting yml file or create a new one

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  codeql:
    name: "CodeQL Security Scan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  devin:
    name: "Devin Remediation Orchestrator"
    runs-on: ubuntu-latest
    needs: codeql   # <-- This forces the job to wait for CodeQL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Devin Security Orchestrator
        uses: Pvpres/devin-security-sentinel@v1
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          branch: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          devin_api_key: ${{ secrets.DEVIN_API_KEY }}
