# =============================================================================
# Devin Security Sentinel - Two Separate Jobs Workflow
# =============================================================================
# This workflow runs CodeQL and Devin remediation as separate jobs.
# Use this when you want to:
#   - See separate job status in GitHub Actions UI
#   - Have clearer separation of concerns
#   - Potentially run other jobs in parallel with CodeQL
# Copy this file to your repository's .github/workflows/ directory.
#
# Prerequisites:
#   1. Add DEVIN_API_KEY to your repository secrets (Settings > Secrets > Actions)
#   2. Optionally add SLACK_BOT_TOKEN and SLACK_CHANNEL_ID for Slack notifications
# =============================================================================

name: "Devin Security Orchestration (Two Jobs)"

# Workflow triggers
on:
  # Manual trigger from GitHub Actions UI
  workflow_dispatch:

  # Automatic trigger on push to main branches
  push:
    branches:
      - main
      - master

jobs:
  # ===========================================================================
  # Job 1: CodeQL Security Scan
  # Runs first to generate security alerts
  # ===========================================================================
  codeql:
    name: "CodeQL Security Scan"
    runs-on: ubuntu-latest

    # Permissions required for code scanning
    permissions:
      contents: read
      security-events: write

    steps:
      # Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Initialize CodeQL with specified languages
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          # Add your project's languages here
          # Supported: python, javascript, typescript, java, csharp, cpp, go, ruby
          languages: python

      # Run the CodeQL analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # ===========================================================================
  # Job 2: Devin Remediation Orchestrator
  # Runs after CodeQL completes (enforced by 'needs' dependency)
  # ===========================================================================
  devin:
    name: "Devin Remediation Orchestrator"
    runs-on: ubuntu-latest

    # Wait for CodeQL job to complete before starting
    # This ensures fresh security alerts are available
    needs: codeql

    # Permissions for accessing security alerts
    permissions:
      contents: read
      security-events: read

    steps:
      # Checkout is required for the action to access repository context
      - name: Checkout repository
        uses: actions/checkout@v4

      # Run Devin Security Sentinel to remediate detected vulnerabilities
      - name: Run Devin Security Orchestrator
        uses: Pvpres/devin-security-sentinel@v1
        with:
          # Required inputs
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          devin_api_key: ${{ secrets.DEVIN_API_KEY }}

          # Optional: specify branch (defaults to triggered branch)
          branch: ${{ github.ref_name }}

          # Optional: Slack integration for real-time updates
          # Provides live progress tracking in your Slack channel
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
